services:
  db:
    image: postgres:15
    container_name: myapp_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  be:
    build: ./be
    container_name: myapp_be
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./be:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  fe:
    build: ./fe
    container_name: myapp_fe
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - be

volumes:
  db_data: